### First we need to load the SQL extension

In [4]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

### We then load the database in this case the database is named: intro_to_sql_for_analytics

In [5]:
%sql postgresql+psycopg://localhost:5432/intro_to_sql_for_analytics

### Basic SQL queries

In [8]:
%%sql

SELECT * 
FROM billboard_top_100_year_end
WHERE index < 5;

 * postgresql+psycopg://localhost:5432/intro_to_sql_for_analytics
5 rows affected.

[(0, 1956, 1, 'Elvis Presley', 'Elvis Presley', 'Heartbreak Hotel', 1.0),
 (1, 1956, 2, 'Elvis Presley', 'Elvis Presley', "Don't Be Cruel", 2.0),
 (2, 1956, 3, 'Nelson Riddle', 'Nelson Riddle', 'Lisbon Antigua', 3.0),
 (3, 1956, 4, 'Platters', 'Platters', 'My Prayer', 4.0),
 (4, 1956, 5, 'Gogi Grant', 'Gogi Grant', 'The Wayward Wind', 5.0)]

In [9]:
%%sql

SELECT song_name 
FROM billboard_top_100_year_end
WHERE year = 1988 AND year_rank = 2;

 * postgresql+psycopg://localhost:5432/intro_to_sql_for_analytics
1 rows affected.

[('Need You Tonight',)]

In [10]:
%%sql

SELECT * 
FROM coaches

 * postgresql+psycopg://localhost:5432/intro_to_sql_for_analytics
91 rows affected.

[(0, 'AGHAKOUCHEKI Abbas', 'Islamic Republic of Iran', 'IRI', 'Wheelchair Basketball', 'WBK', 'Men'),
 (1, 'AKIN Ahmet', 'Turkey', 'TUR', 'Wheelchair Basketball', 'WBK', 'Men'),
 (2, 'AKPWEH Toussaint', 'France', 'FRA', 'Football 5-a-side', 'FB5', 'Men'),
 (3, 'ARIMA Masato', 'Japan', 'JPN', 'Wheelchair Basketball', 'WBK', None),
 (4, 'BAN Nicole', 'Canada', 'CAN', 'Sitting Volleyball', 'VBS', 'Women'),
 (5, 'BARGUEIRAS MARTINEZ Jesus David', 'Spain', 'ESP', 'Football 5-a-side', 'FB5', 'Men'),
 (6, 'BHANIA Haj', 'Great Britain', 'GBR', 'Wheelchair Basketball', 'WBK', None),
 (7, 'BOUTIBA Saad', 'Algeria', 'ALG', 'Goalball', 'GBL', 'Men'),
 (8, 'BRAHIMI Mustapha', 'Algeria', 'ALG', 'Wheelchair Basketball', 'WBK', 'Men'),
 (9, 'CARRION RUIZ Abraham', 'Spain', 'ESP', 'Wheelchair Basketball', 'WBK', 'Women'),
 (10, 'CHEN Qi', "People's Republic of China", 'CHN', 'Wheelchair Basketball', 'WBK', 'Women'),
 (11, 'CHOUDHRY Gaz', 'Great Britain', 'GBR', 'Wheelchair Basketball', 'WBK', 'Men'),
 (12, 'CORR Peter', 'Australia', 'AUS', 'Goalball', 'GBL', 'Women'),
 (13, 'COTE Patrick', 'Canada', 'CAN', 'Wheelchair Rugby', 'WRU', 'Mixed'),
 (14, 'CUSIN Olivier', 'France', 'FRA', 'Wheelchair Rugby', 'WRU', 'Mixed'),
 (15, 'CZECHOWSKI Jake', 'United States of America', 'USA', 'Goalball', 'GBL', 'Women'),
 (16, 'de RICK Johan', 'Belgium', 'BEL', 'Goalball', 'GBL', 'Men'),
 (17, 'DEMONTE Martin', 'Argentina', 'ARG', 'Football 5-a-side', 'FB5', 'Men'),
 (18, 'DO NASCIMENTO CARDOSO Ana Lucia', 'Colombia', 'COL', 'Wheelchair Basketball', 'WBK', 'Men'),
 (19, 'DUBBERLEY Brad', 'Australia', 'AUS', 'Wheelchair Rugby', 'WRU', 'Mixed'),
 (20, 'DUBROVIN Anton', 'Ukraine', 'UKR', 'Goalball', 'GBL', 'Men'),
 (21, 'DUBROVIN Fedir', 'Ukraine', 'UKR', 'Goalball', 'GBL', 'Men'),
 (22, 'DUCHARME Marc Antoine', 'Canada', 'CAN', 'Wheelchair Basketball', 'WBK', 'Women'),
 (23, 'EDRIS Gharib', 'Egypt', 'EGY', 'Sitting Volleyball', 'VBS', None),
 (24, 'EL MOUNTAQI Driss', 'Morocco', 'MAR', 'Football 5-a-side', 'FB5', 'Men'),
 (25, 'ELAIUTY Mosaad', 'Egypt', 'EGY', 'Sitting Volleyball', 'VBS', 'Men'),
 (26, 'ELIA GIMENO Raul', 'Spain', 'ESP', 'Wheelchair Basketball', 'WBK', None),
 (27, 'ELTAYEB Hani', 'Egypt', 'EGY', 'Goalball', 'GBL', 'Women'),
 (28, 'FAREBROTHER Trent', 'Canada', 'CAN', 'Goalball', 'GBL', 'Women'),
 (29, 'FERIANI Matteo', 'Canada', 'CAN', 'Wheelchair Basketball', 'WBK', 'Men'),
 (30, 'FISHER Simon', 'Great Britain', 'GBR', 'Wheelchair Basketball', 'WBK', 'Women'),
 (31, 'FREITAS DO NASCIMENTO Dailton', 'Brazil', 'BRA', 'Goalball', 'GBL', 'Women'),
 (32, 'FRIDAY Craig', 'Australia', 'AUS', 'Wheelchair Basketball', 'WBK', 'Men'),
 (33, 'FRIDAY Craig', 'Australia', 'AUS', 'Wheelchair Basketball', 'WBK', 'Women'),
 (34, 'FURNESS Shane', 'Australia', 'AUS', 'Wheelchair Basketball', 'WBK', None),
 (35, 'GECEVICIUS Valdas', 'Lithuania', 'LTU', 'Goalball', 'GBL', 'Men'),
 (36, 'GUEDES DANTAS Jose', 'Brazil', 'BRA', 'Sitting Volleyball', 'VBS', 'Women'),
 (37, 'GUENTHER Johannes', 'Germany', 'GER', 'Goalball', 'GBL', 'Men'),
 (38, 'GUMBERT James', 'United States of America', 'USA', 'Wheelchair Rugby', 'WRU', 'Mixed'),
 (39, 'HAMITER William', 'United States of America', 'USA', 'Sitting Volleyball', 'VBS', 'Women'),
 (40, 'HRUSTEMOVIC Mirza', 'Bosnia and Herzegovina', 'BIH', 'Sitting Volleyball', 'VBS', 'Men'),
 (41, 'ICHIKAWA Kyoichi', 'Japan', 'JPN', 'Goalball', 'GBL', 'Women'),
 (42, 'IWASA Yoshiaki', 'Japan', 'JPN', 'Wheelchair Basketball', 'WBK', 'Women'),
 (43, 'JOHNSON Lawrence', 'United States of America', 'USA', 'Wheelchair Basketball', 'WBK', 'Women'),
 (44, 'KARASU Gultekin', 'Turkey', 'TUR', 'Goalball', 'GBL', 'Women'),
 (45, 'KIM Hyun Woo', 'Republic of Korea', 'KOR', 'Wheelchair Basketball', 'WBK', None),
 (46, 'KO Kwangyub', 'Republic of Korea', 'KOR', 'Wheelchair Basketball', 'WBK', None),
 (47, 'KO Kwangyub', 'Republic of Korea', 'KOR', 'Wheelchair Basketball', 'WBK', 'Men'),
 (48, 'KONGDANPRAI Kongkiat', 'Thailand', 'THA', 'Football 5-a-side', 'FB5', 'Men'),
 (49, 'KRYVENKO Kseniia', 'Ukraine', 'UKR', 'Sitting Volleyball', 'VBS', None),
 (50, 'KUBO Yoshihiro', 'Japan', 'JPN', 'Sitting Volleyball', 'VBS', 'Men'),
 (51, 'KUDO Rikiya', 'Japan', 'JPN', 'Goalball', 'GBL', 'Men'),
 (52, 'KYOYA Kazuyuki', 'Japan', 'JPN', 'Wheelchair Basketball', 'WBK', 'Men'),
 (53, 'LAWRENCE Matt', 'Great Britain', 'GBR', 'Goalball', 'GBL', None),
 (54, 'LAWRENCE Matt', 'Great Britain', 'GBR', 'Wheelchair Basketball', 'WBK', None),
 (55, 'LYKINS Ron', 'United States of America', 'USA', 'Wheelchair Basketball', 'WBK', 'Men'),
 (56, 'MANO Yoshihisa', 'Japan', 'JPN', 'Sitting Volleyball', 'VBS', 'Women'),
 (57, 'MEDIATO Celio', 'Brazil', 'BRA', 'Sitting Volleyball', 'VBS', 'Men'),
 (58, 'MERTEN Michael', 'Germany', 'GER', 'Sitting Volleyball', 'VBS', 'Men'),
 (59, 'MIKAMI Yukako', 'Japan', 'JPN', 'Goalball', 'GBL', None),
 (60, 'MITCHELL Greg', 'New Zealand', 'NZL', 'Wheelchair Rugby', 'WRU', 'Mixed'),
 (61, 'NABIEV Ilkam', 'RPC', 'RPC', 'Goalball', 'GBL', 'Women'),
 (62, 'NOHL Dennis', 'Germany', 'GER', 'Wheelchair Basketball', 'WBK', 'Women'),
 (63, 'NSENGIYUMVA Jean Marie', 'Rwanda', 'RWA', 'Sitting Volleyball', 'VBS', 'Women'),
 (64, 'ORR Kevin', 'Japan', 'JPN', 'Wheelchair Rugby', 'WRU', 'Mixed'),
 (65, 'OVSYANNIKOV Aleksandr', 'RPC', 'RPC', 'Sitting Volleyball', 'VBS', 'Men'),
 (66, 'OVSYANNIKOV Aleksandr', 'RPC', 'RPC', 'Sitting Volleyball', 'VBS', 'Women'),
 (67, 'PASCIARI Guido', 'Italy', 'ITA', 'Sitting Volleyball', 'VBS', None),
 (68, 'PISKOVA Yuliia', 'Ukraine', 'UKR', 'Sitting Volleyball', 'VBS', None),
 (69, 'RADMORE Colin', 'Great Britain', 'GBR', 'Goalball', 'GBL', None),
 (70, 'RADMORE Colin', 'Great Britain', 'GBR', 'Wheelchair Basketball', 'WBK', None),
 (71, 'REGIER Jason', 'Denmark', 'DEN', 'Wheelchair Rugby', 'WRU', 'Mixed'),
 (72, 'RENCBER Salih', 'Turkey', 'TUR', 'Goalball', 'GBL', 'Men'),
 (73, 'REZAEI Hadi', 'Islamic Republic of Iran', 'IRI', 'Sitting Volleyball', 'VBS', 'Men'),
 (74, 'RIBEIRO Amauri', 'Italy', 'ITA', 'Sitting Volleyball', 'VBS', 'Women'),
 (75, 'RIBEIRO de VASCONCELOS Fabio', 'Brazil', 'BRA', 'Football 5-a-side', 'FB5', 'Men'),
 (76, 'SHAW Paul', 'Great Britain', 'GBR', 'Wheelchair Rugby', 'WRU', 'Mixed'),
 (77, 'SHOHAM Raz', 'Israel', 'ISR', 'Goalball', 'GBL', 'Women'),
 (78, 'TAGHICHE Ahmed', 'Algeria', 'ALG', 'Wheelchair Basketball', 'WBK', 'Women'),
 (79, 'TAKADA Satoshi', 'Japan', 'JPN', 'Football 5-a-side', 'FB5', 'Men'),
 (80, 'TANG Qun', "People's Republic of China", 'CHN', 'Goalball', 'GBL', 'Women'),
 (81, 'TAPIA LOPEZ Genoveva', 'Spain', 'ESP', 'Wheelchair Basketball', 'WBK', None),
 (82, 'TOSIM Alessandro', 'Brazil', 'BRA', 'Goalball', 'GBL', 'Men'),
 (83, 'TRIGO DIEZ Oscar', 'Spain', 'ESP', 'Wheelchair Basketball', 'WBK', 'Men'),
 (84, 'van der LINDEN Gertjan', 'Netherlands', 'NED', 'Wheelchair Basketball', 'WBK', 'Women'),
 (85, 'XU Huimin', "People's Republic of China", 'CHN', 'Sitting Volleyball', 'VBS', 'Women'),
 (86, 'XU Yufei', "People's Republic of China", 'CHN', 'Football 5-a-side', 'FB5', 'Men'),
 (87, 'YE Jing', "People's Republic of China", 'CHN', 'Sitting Volleyball', 'VBS', 'Men'),
 (88, 'YIN Shiqiang', "People's Republic of China", 'CHN', 'Goalball', 'GBL', 'Men'),
 (89, 'YOUNG Keith', 'United States of America', 'USA', 'Goalball', 'GBL', 'Men'),
 (90, 'ZELTINGER Nicolai', 'Germany', 'GER', 'Wheelchair Basketball', 'WBK', 'Men')]

### The LIMIT command

In [11]:
%%sql

SELECT * 
FROM billboard_top_100_year_end
LIMIT 5

 * postgresql+psycopg://localhost:5432/intro_to_sql_for_analytics
5 rows affected.

[(0, 1956, 1, 'Elvis Presley', 'Elvis Presley', 'Heartbreak Hotel', 1.0),
 (1, 1956, 2, 'Elvis Presley', 'Elvis Presley', "Don't Be Cruel", 2.0),
 (2, 1956, 3, 'Nelson Riddle', 'Nelson Riddle', 'Lisbon Antigua', 3.0),
 (3, 1956, 4, 'Platters', 'Platters', 'My Prayer', 4.0),
 (4, 1956, 5, 'Gogi Grant', 'Gogi Grant', 'The Wayward Wind', 5.0)]

In [12]:
%%sql

SELECT * 
FROM billboard_top_100_year_end
LIMIT 15

 * postgresql+psycopg://localhost:5432/intro_to_sql_for_analytics
15 rows affected.

[(0, 1956, 1, 'Elvis Presley', 'Elvis Presley', 'Heartbreak Hotel', 1.0),
 (1, 1956, 2, 'Elvis Presley', 'Elvis Presley', "Don't Be Cruel", 2.0),
 (2, 1956, 3, 'Nelson Riddle', 'Nelson Riddle', 'Lisbon Antigua', 3.0),
 (3, 1956, 4, 'Platters', 'Platters', 'My Prayer', 4.0),
 (4, 1956, 5, 'Gogi Grant', 'Gogi Grant', 'The Wayward Wind', 5.0),
 (5, 1956, 6, 'Les Baxter', 'Les Baxter', 'The Poor People Of Paris', 6.0),
 (6, 1956, 7, 'Doris Day', 'Doris Day', 'Whatever Will Be Will Be (Que Sera Sera)', 7.0),
 (7, 1956, 8, 'Elvis Presley', 'Elvis Presley', 'Hound Dog', 8.0),
 (8, 1956, 9, 'Dean Martin', 'Dean Martin', 'Memories Are Made Of This', 9.0),
 (9, 1956, 10, 'Kay Starr', 'Kay Starr', 'Rock And Roll Waltz', 10.0),
 (10, 1956, 11, 'Morris Stoloff', 'Morris Stoloff', 'Moonglow And Theme From "Picnic"', 11.0),
 (11, 1956, 12, 'Platters', 'Platters', 'The Great Pretender', 12.0),
 (12, 1956, 13, 'Pat Boone', 'Pat Boone', 'I Almost Lost My Mind', 13.0),
 (13, 1956, 14, 'Elvis Presley', 'Elvis Presley', 'I Want You, I Need You, I Love You', 14.0),
 (14, 1956, 15, 'Elvis Presley', 'Elvis Presley', 'Love Me Tender', 15.0)]

In [13]:
%%sql

SELECT * 
FROM billboard_top_100_year_end
WHERE artist = 'Mariah Carey'
LIMIT 10

 * postgresql+psycopg://localhost:5432/intro_to_sql_for_analytics
10 rows affected.

[(3502, 1990, 6, 'Mariah Carey', 'Mariah Carey', 'Vision Of Love', 3503.0),
 (3574, 1990, 76, 'Mariah Carey', 'Mariah Carey', 'Love Takes Time', 3575.0),
 (3611, 1991, 13, 'Mariah Carey', 'Mariah Carey', 'Someday', 3612.0),
 (3621, 1991, 22, 'Mariah Carey', 'Mariah Carey', 'Emotions', 3622.0),
 (3625, 1991, 26, 'Mariah Carey', 'Mariah Carey', "I Don't Wanna Cry", 3626.0),
 (3668, 1991, 69, 'Mariah Carey', 'Mariah Carey', 'Love Takes Time', 3669.0),
 (3715, 1992, 16, 'Mariah Carey', 'Mariah Carey', "I'll Be There", 3716.0),
 (3723, 1992, 23, 'Mariah Carey', 'Mariah Carey', "Can't Let Go", 3724.0),
 (3745, 1992, 42, 'Mariah Carey', 'Mariah Carey', 'Make It Happen', 3746.0),
 (3811, 1993, 8, 'Mariah Carey', 'Mariah Carey', 'Dreamlover', 3812.0)]

In [14]:
%%sql

SELECT * 
FROM billboard_top_100_year_end
WHERE year_rank = 1
LIMIT 10

 * postgresql+psycopg://localhost:5432/intro_to_sql_for_analytics
10 rows affected.

[(0, 1956, 1, 'Elvis Presley', 'Elvis Presley', 'Heartbreak Hotel', 1.0),
 (103, 1957, 1, 'Elvis Presley', 'Elvis Presley', 'All Shook Up', 104.0),
 (203, 1958, 1, 'Domenico Modugno', 'Domenico Modugno', 'Volare (Nel Blu Dipinto Di Blu)', 204.0),
 (304, 1959, 1, 'Johnny Horton', 'Johnny Horton', 'The Battle Of New Orleans', 305.0),
 (406, 1960, 1, 'Percy Faith', 'Percy Faith', 'Theme From "A Summer Place"', 407.0),
 (508, 1961, 1, 'Bobby Lewis', 'Bobby Lewis', "Tossin' And Turnin'", 509.0),
 (608, 1962, 1, 'Mr. Acker Bilk', 'Mr. Acker Bilk', 'Stranger On The Shore', 609.0),
 (708, 1963, 1, 'Jimmy Gilmer and The Fireballs', 'Jimmy Gilmer and The Fireballs', 'Sugar Shack', 709.0),
 (809, 1964, 1, 'Beatles', 'Beatles', 'I Want To Hold Your Hand', 810.0),
 (911, 1965, 1, 'Sam The Sham and The Pharaohs', 'Sam The Sham and The Pharaohs', 'Wooly Bully', 912.0)]

### ORDER BY

In [18]:
%%sql

SELECT *
  FROM billboard_top_100_year_end
  ORDER BY artist
  LIMIT 20;

 * postgresql+psycopg://localhost:5432/intro_to_sql_for_analytics
20 rows affected.

[(4740, 2001, 51, "'N Sync", "'N Sync", 'This I Promise You', 4741.0),
 (4848, 2002, 33, "'N Sync feat. Nelly", "'N Sync", 'Girlfriend', 4849.0),
 (4365, 1998, 37, "'N Sync", "'N Sync", 'I Want You Back', 4366.0),
 (4909, 2002, 75, "'N Sync", "'N Sync", 'Gone', 4910.0),
 (4490, 1999, 45, "'N Sync", "'N Sync", '(God Must Have Spent) A Little More Time On You', 4491.0),
 (4590, 2000, 27, "'N Sync", "'N Sync", "It's Gonna Be Me", 4591.0),
 (4584, 2000, 21, "'N Sync", "'N Sync", 'Bye Bye Bye', 4585.0),
 (4561, 1999, 100, "Alabama feat. 'N Sync", "'N Sync", 'God Must Have Spent A Little More Time On You', 4562.0),
 (4555, 1999, 97, "'N Sync and Gloria Estefan", "'N Sync", 'Music Of My Heart', 4556.0),
 (3046, 1985, 68, "'Til Tuesday", "'Til Tuesday", 'Voices Carry', 3047.0),
 (3457, 1989, 63, '.38 Special', '.38 Special', 'Second Chances', 3458.0),
 (3951, 1994, 40, '10,000 Maniacs', '10,000 Maniacs', 'Because The Night', 3952.0),
 (1500, 1970, 84, '100 Proof Aged In Soul', '100 Proof Aged In Soul', "Somebody's Been Sleeping", 1501.0),
 (2177, 1977, 44, '10cc', '10cc', 'The Things We Do For Love', 2178.0),
 (1967, 1975, 42, '10cc', '10cc', "I'm Not In Love", 1968.0),
 (4701, 2001, 20, '112', '112', 'Peaches and Cream', 4702.0),
 (4149, 1996, 34, '112 feat. The Notorious B.I.G.', '112', 'Only You', 4150.0),
 (4260, 1997, 37, '112', '112', 'Cupid', 4261.0),
 (4492, 1999, 47, "112 feat. Lil' Zane", '112', 'Anywhere', 4493.0),
 (4268, 1997, 43, 'Allure feat. 112', '112', 'All Cried Out', 4269.0)]

In the cell below we have order the table using the artist column in alphabetical order and then ordering the year_rank in numerical order.

So we can see the artists in alphabetical order and their highest ranked songs displayed first.

In [20]:
%%sql

SELECT *
  FROM billboard_top_100_year_end
  ORDER BY artist, year_rank
  LIMIT 30;

 * postgresql+psycopg://localhost:5432/intro_to_sql_for_analytics
30 rows affected.

[(4584, 2000, 21, "'N Sync", "'N Sync", 'Bye Bye Bye', 4585.0),
 (4590, 2000, 27, "'N Sync", "'N Sync", "It's Gonna Be Me", 4591.0),
 (4848, 2002, 33, "'N Sync feat. Nelly", "'N Sync", 'Girlfriend', 4849.0),
 (4365, 1998, 37, "'N Sync", "'N Sync", 'I Want You Back', 4366.0),
 (4490, 1999, 45, "'N Sync", "'N Sync", '(God Must Have Spent) A Little More Time On You', 4491.0),
 (4740, 2001, 51, "'N Sync", "'N Sync", 'This I Promise You', 4741.0),
 (4909, 2002, 75, "'N Sync", "'N Sync", 'Gone', 4910.0),
 (4555, 1999, 97, "'N Sync and Gloria Estefan", "'N Sync", 'Music Of My Heart', 4556.0),
 (4561, 1999, 100, "Alabama feat. 'N Sync", "'N Sync", 'God Must Have Spent A Little More Time On You', 4562.0),
 (3046, 1985, 68, "'Til Tuesday", "'Til Tuesday", 'Voices Carry', 3047.0),
 (3457, 1989, 63, '.38 Special', '.38 Special', 'Second Chances', 3458.0),
 (3951, 1994, 40, '10,000 Maniacs', '10,000 Maniacs', 'Because The Night', 3952.0),
 (1500, 1970, 84, '100 Proof Aged In Soul', '100 Proof Aged In Soul', "Somebody's Been Sleeping", 1501.0),
 (1967, 1975, 42, '10cc', '10cc', "I'm Not In Love", 1968.0),
 (2177, 1977, 44, '10cc', '10cc', 'The Things We Do For Love', 2178.0),
 (4701, 2001, 20, '112', '112', 'Peaches and Cream', 4702.0),
 (4149, 1996, 34, '112 feat. The Notorious B.I.G.', '112', 'Only You', 4150.0),
 (4260, 1997, 37, '112', '112', 'Cupid', 4261.0),
 (4268, 1997, 43, 'Allure feat. 112', '112', 'All Cried Out', 4269.0),
 (4492, 1999, 47, "112 feat. Lil' Zane", '112', 'Anywhere', 4493.0),
 (4760, 2001, 68, '112', '112', "It's Over Now", 4761.0),
 (4419, 1998, 84, 'Allure feat. 112', '112', 'All Cried Out', 4420.0),
 (5349, 2005, 97, '112 feat. Foxy Brown', '112', 'U Already Know', 5350.0),
 (1246, 1968, 33, '1910 Fruitgum Company', '1910 Fruitgum Company', 'Simon Says', 1247.0),
 (1261, 1968, 48, '1910 Fruitgum Company', '1910 Fruitgum Company', '1, 2, 3, Red Light', 1262.0),
 (1383, 1969, 67, '1910 Fruitgum Company', '1910 Fruitgum Company', 'Indian Giver', 1384.0),
 (6239, 2012, 27, 'Kanye West, Big Sean, Pusha T, 2 Chainz', '2 Chainz', 'Mercy', 6240.0),
 (6396, 2013, 41, 'A$AP Rocky feat. Drake, 2 Chainz and Kendrick Lamar', '2 Chainz', 'F**kin Problems', 6397.0),
 (6278, 2012, 54, '2 Chainz feat. Drake', '2 Chainz', 'No Lie', 6279.0),
 (6474, 2013, 99, '2 Chainz', '2 Chainz', "I'm Different", 6475.0)]

### Descending order using DESC

In [21]:
%%sql
SELECT *
  FROM billboard_top_100_year_end
  ORDER BY artist DESC, year_rank
  LIMIT 20;

 * postgresql+psycopg://localhost:5432/intro_to_sql_for_analytics
20 rows affected.

[(307, 1959, 4, 'Frankie Avalon', None, 'Venus', 308.0),
 (425, 1960, 20, 'Roy Orbison', None, 'Only The Lonely', 426.0),
 (3001, 1985, 24, 'Bryan Adams', None, 'Heaven', 3002.0),
 (3641, 1991, 42, 'Whitney Houston', None, "I'm Your Baby Tonight", 3642.0),
 (5279, 2005, 42, 'Chris Brown', None, 'Run It!', 5280.0),
 (684, 1962, 77, 'Rick Nelson', None, 'Teen Age Idol', 685.0),
 (592, 1961, 85, 'Paul Anka', None, 'Tonight My Love, Tonight', 593.0),
 (4317, 1997, 89, 'Michael Bolton', None, 'Go The Distance', 4318.0),
 (5897, 2009, 94, 'Zac Brown Band', None, 'Whatever It Is', 5898.0),
 (5914, 2010, 5, 'Usher feat. will.i.am', 'will.i.am', 'OMG', 5915.0),
 (6367, 2013, 23, 'will.i.am and Britney Spears', 'will.i.am', 'Scream and Shout', 6368.0),
 (5715, 2008, 59, 'Flo Rida feat. will.i.am', 'will.i.am', 'In The Ayer', 5716.0),
 (5470, 2006, 84, 'The Pussycat Dolls feat. will.i.am', 'will.i.am', 'Beep', 5471.0),
 (6455, 2013, 85, 'The Script feat. will.i.am', 'will.i.am', 'Hall Of Fame', 6456.0),
 (6469, 2013, 95, 'will.i.am feat. Justin Bieber', 'will.i.am', '#thatPOWER', 6470.0),
 (4635, 2000, 66, 'soulDecision feat. Thrust', 'soulDecision', 'Faded', 4636.0),
 (4944, 2003, 6, 'matchbox twenty', 'matchbox twenty', 'Unwell', 4945.0),
 (4682, 2001, 6, 'matchbox twenty', 'matchbox twenty', "If You're Gone", 4683.0),
 (4572, 2000, 9, 'matchbox twenty', 'matchbox twenty', 'Bent', 4573.0),
 (6205, 2012, 3, 'fun. feat. Janelle Monae', 'fun.', 'We Are Young', 6206.0)]

In [22]:
%%sql
SELECT *
  FROM billboard_top_100_year_end
  ORDER BY artist, year_rank DESC
  LIMIT 20;

 * postgresql+psycopg://localhost:5432/intro_to_sql_for_analytics
20 rows affected.

[(4561, 1999, 100, "Alabama feat. 'N Sync", "'N Sync", 'God Must Have Spent A Little More Time On You', 4562.0),
 (4555, 1999, 97, "'N Sync and Gloria Estefan", "'N Sync", 'Music Of My Heart', 4556.0),
 (4909, 2002, 75, "'N Sync", "'N Sync", 'Gone', 4910.0),
 (4740, 2001, 51, "'N Sync", "'N Sync", 'This I Promise You', 4741.0),
 (4490, 1999, 45, "'N Sync", "'N Sync", '(God Must Have Spent) A Little More Time On You', 4491.0),
 (4365, 1998, 37, "'N Sync", "'N Sync", 'I Want You Back', 4366.0),
 (4848, 2002, 33, "'N Sync feat. Nelly", "'N Sync", 'Girlfriend', 4849.0),
 (4590, 2000, 27, "'N Sync", "'N Sync", "It's Gonna Be Me", 4591.0),
 (4584, 2000, 21, "'N Sync", "'N Sync", 'Bye Bye Bye', 4585.0),
 (3046, 1985, 68, "'Til Tuesday", "'Til Tuesday", 'Voices Carry', 3047.0),
 (3457, 1989, 63, '.38 Special', '.38 Special', 'Second Chances', 3458.0),
 (3951, 1994, 40, '10,000 Maniacs', '10,000 Maniacs', 'Because The Night', 3952.0),
 (1500, 1970, 84, '100 Proof Aged In Soul', '100 Proof Aged In Soul', "Somebody's Been Sleeping", 1501.0),
 (2177, 1977, 44, '10cc', '10cc', 'The Things We Do For Love', 2178.0),
 (1967, 1975, 42, '10cc', '10cc', "I'm Not In Love", 1968.0),
 (5349, 2005, 97, '112 feat. Foxy Brown', '112', 'U Already Know', 5350.0),
 (4419, 1998, 84, 'Allure feat. 112', '112', 'All Cried Out', 4420.0),
 (4760, 2001, 68, '112', '112', "It's Over Now", 4761.0),
 (4492, 1999, 47, "112 feat. Lil' Zane", '112', 'Anywhere', 4493.0),
 (4268, 1997, 43, 'Allure feat. 112', '112', 'All Cried Out', 4269.0)]

In [23]:
%%sql
SELECT *
  FROM billboard_top_100_year_end
  ORDER BY artist DESC, year_rank DESC
  LIMIT 20;

 * postgresql+psycopg://localhost:5432/intro_to_sql_for_analytics
20 rows affected.

[(5897, 2009, 94, 'Zac Brown Band', None, 'Whatever It Is', 5898.0),
 (4317, 1997, 89, 'Michael Bolton', None, 'Go The Distance', 4318.0),
 (592, 1961, 85, 'Paul Anka', None, 'Tonight My Love, Tonight', 593.0),
 (684, 1962, 77, 'Rick Nelson', None, 'Teen Age Idol', 685.0),
 (3641, 1991, 42, 'Whitney Houston', None, "I'm Your Baby Tonight", 3642.0),
 (5279, 2005, 42, 'Chris Brown', None, 'Run It!', 5280.0),
 (3001, 1985, 24, 'Bryan Adams', None, 'Heaven', 3002.0),
 (425, 1960, 20, 'Roy Orbison', None, 'Only The Lonely', 426.0),
 (307, 1959, 4, 'Frankie Avalon', None, 'Venus', 308.0),
 (6469, 2013, 95, 'will.i.am feat. Justin Bieber', 'will.i.am', '#thatPOWER', 6470.0),
 (6455, 2013, 85, 'The Script feat. will.i.am', 'will.i.am', 'Hall Of Fame', 6456.0),
 (5470, 2006, 84, 'The Pussycat Dolls feat. will.i.am', 'will.i.am', 'Beep', 5471.0),
 (5715, 2008, 59, 'Flo Rida feat. will.i.am', 'will.i.am', 'In The Ayer', 5716.0),
 (6367, 2013, 23, 'will.i.am and Britney Spears', 'will.i.am', 'Scream and Shout', 6368.0),
 (5914, 2010, 5, 'Usher feat. will.i.am', 'will.i.am', 'OMG', 5915.0),
 (4635, 2000, 66, 'soulDecision feat. Thrust', 'soulDecision', 'Faded', 4636.0),
 (4572, 2000, 9, 'matchbox twenty', 'matchbox twenty', 'Bent', 4573.0),
 (4682, 2001, 6, 'matchbox twenty', 'matchbox twenty', "If You're Gone", 4683.0),
 (4944, 2003, 6, 'matchbox twenty', 'matchbox twenty', 'Unwell', 4945.0),
 (6443, 2013, 76, 'fun.', 'fun.', 'Carry On', 6444.0)]